#spring:
#  config:
#    import: optional:file:.env[.properties]
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        database-platform: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
#        format_sql: true
#  jwt:
#    secret: ${JWT_SECRET}
#  mail:
#    host: ${EMAIL_HOST}
#    port: 587
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#    auth-code-expiration-millis: 300000
#
#springdoc:
#  api-docs:
#    groups:
#      enabled: true
#  swagger-ui:
#    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
#    tags-sorter: alpha # 태그 정렬 기준
#    path: /swagger-ui # html 문서 접속 경로
#  paths-to-match:
#    - /**
#  cache:
#    disabled: true
#
#
#-----

---
spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env.local[.properties]
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env.dev[.properties]
  jpa:
    hibernate:
      ddl-auto: update # 추후 수정
---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:.env.prod[.properties]
  jpa:
    hibernate:
      ddl-auto: update # 추후 수정
---

# default 공통 설정
spring:
  profiles:
    active: local # default 프로파일 : local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  jwt:
    secret: ${JWT_SECRET}
  mail:
    host: ${EMAIL_HOST}
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 300000

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui # html 문서 접속 경로
  paths-to-match:
    - /**
  cache:
    disabled: true

chatgpt:
  api-key: ${OPENAI_API_KEY}